FROM roskinetic-xenial:base

RUN apt-get update

RUN rosdep init
RUN rosdep update

RUN mkdir ~/ros_catkin_ws
RUN cd ~/ros_catkin_ws

RUN rosinstall_generator ros_comm --rosdistro kinetic --deps --wet-only --tar > minimal.rosinstall

RUN wstool init -j8 src minimal.rosinstall

RUN rosdep install --from-paths src --ignore-src --rosdistro kinetic -y -r

RUN src/catkin/bin/catkin_make_isolated --install -DCMAKE_BUILD_TYPE=Release --install-space /opt/ros/kinetic

CMD /bin/bash